function d2x = boom_2(v)
   
%    I_tot = 150000; l_B = 12;m_B = 5500;I_B = 67220;l_J = 10;m_J = 5650;I_J = 51040;g = 9.81; m = 1000;
%    
   
   I_tot=250;   l_B=2.5;     m_B=300;     I_B=156.25;     l_J=2;     m_J=250;     I_J=85;     g=9.81;       m=90;
   
   q_d = v(1:4);
   q = v(5:10);
   dq = v(11:16);
   
   err_a = q_d(1)-q(1);
   err_b = q_d(2)-q(2);
   err_g = q_d(3)-q(3);
   err_l = q_d(4)-q(4);
   
   th1 = q(1);
   th2 = q(2);
   th3 = q(3);
   d6 = q(4);
   th4 = q(5);
   th5 = q(6);
   
   dth1 = dq(1);
   dth2 = dq(2);
   dth3 = dq(3);
   dd6 = dq(4);
   dth4 = dq(5);
   dth5  = dq(6);
   
  
   M = [ I_tot + d6^2*m + l_B^2*m*cos(th2)^2 + l_J^2*m*cos(th3)^2 + (l_B^2*m_B*cos(th2)^2)/4 + l_B^2*m_J*cos(th2)^2 + (l_J^2*m_J*cos(th3)^2)/4 - d6^2*m*cos(th4)^2*cos(th5)^2 + 2*l_B*l_J*m*cos(th2)*cos(th3) + l_B*l_J*m_J*cos(th2)*cos(th3) + 2*d6*l_B*m*cos(th2)*sin(th5) + 2*d6*l_J*m*cos(th3)*sin(th5),                          d6*l_B*m*cos(th5)*sin(th2)*sin(th4),                          d6*l_J*m*cos(th5)*sin(th3)*sin(th4),            m*cos(th5)*sin(th4)*(l_B*cos(th2) + l_J*cos(th3)), d6*m*cos(th4)*cos(th5)*(l_B*cos(th2) + l_J*cos(th3) + d6*sin(th5)), -d6*m*sin(th4)*(d6 + l_B*cos(th2)*sin(th5) + l_J*cos(th3)*sin(th5));
                                                                                                                                                                                                                                                                 d6*l_B*m*cos(th5)*sin(th2)*sin(th4),                    I_B + l_B^2*m + (l_B^2*m_B)/4 + l_B^2*m_J,                       (l_B*l_J*cos(th2 - th3)*(2*m + m_J))/2, - l_B*m*sin(th2)*sin(th5) - l_B*m*cos(th2)*cos(th4)*cos(th5),                                d6*l_B*m*cos(th2)*cos(th5)*sin(th4),          -d6*l_B*m*(cos(th5)*sin(th2) - cos(th2)*cos(th4)*sin(th5));
                                                                                                                                                                                                                                                                d6*l_J*m*cos(th5)*sin(th3)*sin(th4),                       (l_B*l_J*cos(th2 - th3)*(2*m + m_J))/2,                                I_J + l_J^2*m + (l_J^2*m_J)/4, - l_J*m*sin(th3)*sin(th5) - l_J*m*cos(th3)*cos(th4)*cos(th5),                                d6*l_J*m*cos(th3)*cos(th5)*sin(th4),          -d6*l_J*m*(cos(th5)*sin(th3) - cos(th3)*cos(th4)*sin(th5));
                                                                                                                                                                                                                                                  m*cos(th5)*sin(th4)*(l_B*cos(th2) + l_J*cos(th3)), - l_B*m*sin(th2)*sin(th5) - l_B*m*cos(th2)*cos(th4)*cos(th5), - l_J*m*sin(th3)*sin(th5) - l_J*m*cos(th3)*cos(th4)*cos(th5),                                                            m,                                                                  0,                                                                   0;
                                                                                                                                                                                                                                 d6*m*cos(th4)*cos(th5)*(l_B*cos(th2) + l_J*cos(th3) + d6*sin(th5)),                          d6*l_B*m*cos(th2)*cos(th5)*sin(th4),                          d6*l_J*m*cos(th3)*cos(th5)*sin(th4),                                                            0,                                           -d6^2*m*(sin(th5)^2 - 1),                                                                   0;
                                                                                                                                                                                                                                -d6*m*sin(th4)*(d6 + l_B*cos(th2)*sin(th5) + l_J*cos(th3)*sin(th5)),   -d6*l_B*m*(cos(th5)*sin(th2) - cos(th2)*cos(th4)*sin(th5)),   -d6*l_J*m*(cos(th5)*sin(th3) - cos(th3)*cos(th4)*sin(th5)),                                                            0,                                                                  0,                                                              d6^2*m];
                                                                                                                                                                                                                            
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 
  C = [ 2*d6*dd6*m - dth2*l_B^2*m*sin(2*th2) - dth3*l_J^2*m*sin(2*th3) - (dth2*l_B^2*m_B*sin(2*th2))/4 - dth2*l_B^2*m_J*sin(2*th2) - (dth3*l_J^2*m_J*sin(2*th3))/4 - 2*d6*dd6*m*cos(th4)^2*cos(th5)^2 + 2*dd6*l_B*m*cos(th2)*sin(th5) + 2*dd6*l_J*m*cos(th3)*sin(th5) + 2*d6*dth5*l_B*m*cos(th2)*cos(th5) + 2*d6*dth5*l_J*m*cos(th3)*cos(th5) - 2*dth2*l_B*l_J*m*cos(th3)*sin(th2) - 2*dth3*l_B*l_J*m*cos(th2)*sin(th3) - dth2*l_B*l_J*m_J*cos(th3)*sin(th2) - dth3*l_B*l_J*m_J*cos(th2)*sin(th3) - 2*d6*dth2*l_B*m*sin(th2)*sin(th5) - 2*d6*dth3*l_J*m*sin(th3)*sin(th5) + 2*d6^2*dth4*m*cos(th4)*cos(th5)^2*sin(th4) + 2*d6^2*dth5*m*cos(th4)^2*cos(th5)*sin(th5),                                                                                                                                                                                                                                                         dd6*l_B*m*cos(th5)*sin(th2)*sin(th4) + d6*dth2*l_B*m*cos(th2)*cos(th5)*sin(th4) + d6*dth4*l_B*m*cos(th4)*cos(th5)*sin(th2) - d6*dth5*l_B*m*sin(th2)*sin(th4)*sin(th5),                                                                                                                                                                                                                                                         dd6*l_J*m*cos(th5)*sin(th3)*sin(th4) + d6*dth3*l_J*m*cos(th3)*cos(th5)*sin(th4) + d6*dth4*l_J*m*cos(th4)*cos(th5)*sin(th3) - d6*dth5*l_J*m*sin(th3)*sin(th4)*sin(th5),       dth4*l_B*m*cos(th2)*cos(th4)*cos(th5) + dth4*l_J*m*cos(th3)*cos(th4)*cos(th5) - dth2*l_B*m*cos(th5)*sin(th2)*sin(th4) - dth5*l_B*m*cos(th2)*sin(th4)*sin(th5) - dth3*l_J*m*cos(th5)*sin(th3)*sin(th4) - dth5*l_J*m*cos(th3)*sin(th4)*sin(th5), 2*d6^2*dth5*m*cos(th4)*cos(th5)^2 - d6^2*dth5*m*cos(th4) + dd6*l_B*m*cos(th2)*cos(th4)*cos(th5) + dd6*l_J*m*cos(th3)*cos(th4)*cos(th5) + 2*d6*dd6*m*cos(th4)*cos(th5)*sin(th5) - d6^2*dth4*m*cos(th5)*sin(th4)*sin(th5) - d6*dth2*l_B*m*cos(th4)*cos(th5)*sin(th2) - d6*dth4*l_B*m*cos(th2)*cos(th5)*sin(th4) - d6*dth5*l_B*m*cos(th2)*cos(th4)*sin(th5) - d6*dth3*l_J*m*cos(th4)*cos(th5)*sin(th3) - d6*dth4*l_J*m*cos(th3)*cos(th5)*sin(th4) - d6*dth5*l_J*m*cos(th3)*cos(th4)*sin(th5), d6*dth2*l_B*m*sin(th2)*sin(th4)*sin(th5) - d6^2*dth4*m*cos(th4) - dd6*l_B*m*cos(th2)*sin(th4)*sin(th5) - dd6*l_J*m*cos(th3)*sin(th4)*sin(th5) - d6*dth4*l_B*m*cos(th2)*cos(th4)*sin(th5) - d6*dth5*l_B*m*cos(th2)*cos(th5)*sin(th4) - d6*dth4*l_J*m*cos(th3)*cos(th4)*sin(th5) - d6*dth5*l_J*m*cos(th3)*cos(th5)*sin(th4) - 2*d6*dd6*m*sin(th4) + d6*dth3*l_J*m*sin(th3)*sin(th4)*sin(th5);
                                                                                                                                                                                                                                                     (dth1*l_B^2*m*sin(2*th2))/2 + (dth1*l_B^2*m_B*sin(2*th2))/8 + (dth1*l_B^2*m_J*sin(2*th2))/2 + (3*dd6*l_B*m*cos(th5)*sin(th2)*sin(th4))/2 + dth1*l_B*l_J*m*cos(th3)*sin(th2) + (dth1*l_B*l_J*m_J*cos(th3)*sin(th2))/2 + d6*dth1*l_B*m*sin(th2)*sin(th5) + (d6*dth2*l_B*m*cos(th2)*cos(th5)*sin(th4))/2 + (3*d6*dth4*l_B*m*cos(th4)*cos(th5)*sin(th2))/2 - (3*d6*dth5*l_B*m*sin(th2)*sin(th4)*sin(th5))/2, (dd6*l_B*m*cos(th2)*sin(th5))/2 - (dd6*l_B*m*cos(th4)*cos(th5)*sin(th2))/2 + (d6*dth5*l_B*m*cos(th2)*cos(th5))/2 - (dth3*l_B*l_J*m*cos(th2)*sin(th3))/2 + (dth3*l_B*l_J*m*cos(th3)*sin(th2))/2 - (dth3*l_B*l_J*m_J*cos(th2)*sin(th3))/4 + (dth3*l_B*l_J*m_J*cos(th3)*sin(th2))/4 - (d6*dth1*l_B*m*cos(th2)*cos(th5)*sin(th4))/2 + (d6*dth4*l_B*m*cos(th5)*sin(th2)*sin(th4))/2 + (d6*dth5*l_B*m*cos(th4)*sin(th2)*sin(th5))/2,                                                                                                                                                                                                                                                                                                                                                                       -(l_B*l_J*sin(th2 - th3)*(dth2 - 2*dth3)*(2*m + m_J))/4,             (dth2*l_B*m*cos(th4)*cos(th5)*sin(th2))/2 - dth5*l_B*m*cos(th5)*sin(th2) - (dth2*l_B*m*cos(th2)*sin(th5))/2 + dth4*l_B*m*cos(th2)*cos(th5)*sin(th4) + dth5*l_B*m*cos(th2)*cos(th4)*sin(th5) + (dth1*l_B*m*cos(th5)*sin(th2)*sin(th4))/2,                                                                                                                                                                                                                                                                  dd6*l_B*m*cos(th2)*cos(th5)*sin(th4) + d6*dth4*l_B*m*cos(th2)*cos(th4)*cos(th5) + (d6*dth1*l_B*m*cos(th4)*cos(th5)*sin(th2))/2 - (d6*dth2*l_B*m*cos(th5)*sin(th2)*sin(th4))/2 - d6*dth5*l_B*m*cos(th2)*sin(th4)*sin(th5),                                                             dd6*l_B*m*cos(th2)*cos(th4)*sin(th5) - dd6*l_B*m*cos(th5)*sin(th2) - (d6*dth2*l_B*m*cos(th2)*cos(th5))/2 + d6*dth5*l_B*m*sin(th2)*sin(th5) + d6*dth5*l_B*m*cos(th2)*cos(th4)*cos(th5) - (d6*dth2*l_B*m*cos(th4)*sin(th2)*sin(th5))/2 - d6*dth4*l_B*m*cos(th2)*sin(th4)*sin(th5) - (d6*dth1*l_B*m*sin(th2)*sin(th4)*sin(th5))/2;
                                                                                                                                                                                                                                                                                     (dth1*l_J^2*m*sin(2*th3))/2 + (dth1*l_J^2*m_J*sin(2*th3))/8 + (3*dd6*l_J*m*cos(th5)*sin(th3)*sin(th4))/2 + dth1*l_B*l_J*m*cos(th2)*sin(th3) + (dth1*l_B*l_J*m_J*cos(th2)*sin(th3))/2 + d6*dth1*l_J*m*sin(th3)*sin(th5) + (d6*dth3*l_J*m*cos(th3)*cos(th5)*sin(th4))/2 + (3*d6*dth4*l_J*m*cos(th4)*cos(th5)*sin(th3))/2 - (3*d6*dth5*l_J*m*sin(th3)*sin(th4)*sin(th5))/2,                                                                                                                                                                                                                                                                                                                                                                       -(l_B*l_J*sin(th2 - th3)*(2*m + m_J)*(2*dth2 - dth3))/4, (dd6*l_J*m*cos(th3)*sin(th5))/2 - (dd6*l_J*m*cos(th4)*cos(th5)*sin(th3))/2 + (d6*dth5*l_J*m*cos(th3)*cos(th5))/2 + (dth2*l_B*l_J*m*cos(th2)*sin(th3))/2 - (dth2*l_B*l_J*m*cos(th3)*sin(th2))/2 + (dth2*l_B*l_J*m_J*cos(th2)*sin(th3))/4 - (dth2*l_B*l_J*m_J*cos(th3)*sin(th2))/4 - (d6*dth1*l_J*m*cos(th3)*cos(th5)*sin(th4))/2 + (d6*dth4*l_J*m*cos(th5)*sin(th3)*sin(th4))/2 + (d6*dth5*l_J*m*cos(th4)*sin(th3)*sin(th5))/2,             (dth3*l_J*m*cos(th4)*cos(th5)*sin(th3))/2 - dth5*l_J*m*cos(th5)*sin(th3) - (dth3*l_J*m*cos(th3)*sin(th5))/2 + dth4*l_J*m*cos(th3)*cos(th5)*sin(th4) + dth5*l_J*m*cos(th3)*cos(th4)*sin(th5) + (dth1*l_J*m*cos(th5)*sin(th3)*sin(th4))/2,                                                                                                                                                                                                                                                                  dd6*l_J*m*cos(th3)*cos(th5)*sin(th4) + d6*dth4*l_J*m*cos(th3)*cos(th4)*cos(th5) + (d6*dth1*l_J*m*cos(th4)*cos(th5)*sin(th3))/2 - (d6*dth3*l_J*m*cos(th5)*sin(th3)*sin(th4))/2 - d6*dth5*l_J*m*cos(th3)*sin(th4)*sin(th5),                                                             dd6*l_J*m*cos(th3)*cos(th4)*sin(th5) - dd6*l_J*m*cos(th5)*sin(th3) - (d6*dth3*l_J*m*cos(th3)*cos(th5))/2 + d6*dth5*l_J*m*sin(th3)*sin(th5) + d6*dth5*l_J*m*cos(th3)*cos(th4)*cos(th5) - (d6*dth3*l_J*m*cos(th4)*sin(th3)*sin(th5))/2 - d6*dth4*l_J*m*cos(th3)*sin(th4)*sin(th5) - (d6*dth1*l_J*m*sin(th3)*sin(th4)*sin(th5))/2;
                                                                                                                                                                                                           d6*dth5*m*sin(th4) - d6*dth1*m + d6*dth1*m*cos(th4)^2*cos(th5)^2 - dth1*l_B*m*cos(th2)*sin(th5) - dth1*l_J*m*cos(th3)*sin(th5) + (dth4*l_B*m*cos(th2)*cos(th4)*cos(th5))/2 + (dth4*l_J*m*cos(th3)*cos(th4)*cos(th5))/2 - d6*dth4*m*cos(th4)*cos(th5)*sin(th5) - (3*dth2*l_B*m*cos(th5)*sin(th2)*sin(th4))/2 - (dth5*l_B*m*cos(th2)*sin(th4)*sin(th5))/2 - (3*dth3*l_J*m*cos(th5)*sin(th3)*sin(th4))/2 - (dth5*l_J*m*cos(th3)*sin(th4)*sin(th5))/2,                                                                                                                                                                                   dth2*l_B*m*cos(th4)*cos(th5)*sin(th2) - (dth5*l_B*m*cos(th5)*sin(th2))/2 - dth2*l_B*m*cos(th2)*sin(th5) + (dth4*l_B*m*cos(th2)*cos(th5)*sin(th4))/2 + (dth5*l_B*m*cos(th2)*cos(th4)*sin(th5))/2 - (dth1*l_B*m*cos(th5)*sin(th2)*sin(th4))/2,                                                                                                                                                                                   dth3*l_J*m*cos(th4)*cos(th5)*sin(th3) - (dth5*l_J*m*cos(th5)*sin(th3))/2 - dth3*l_J*m*cos(th3)*sin(th5) + (dth4*l_J*m*cos(th3)*cos(th5)*sin(th4))/2 + (dth5*l_J*m*cos(th3)*cos(th4)*sin(th5))/2 - (dth1*l_J*m*cos(th5)*sin(th3)*sin(th4))/2,                                                                                                                                                                                                                                                   0,                                                                                                                                                                                                                                                                                                    -(m*cos(th5)*(2*d6*dth4*cos(th5) + dth1*l_B*cos(th2)*cos(th4) + dth1*l_J*cos(th3)*cos(th4) + 2*d6*dth1*cos(th4)*sin(th5) + dth2*l_B*cos(th2)*sin(th4) + dth3*l_J*cos(th3)*sin(th4)))/2,                                                                                                       d6*dth1*m*sin(th4) - d6*dth5*m + (dth2*l_B*m*cos(th5)*sin(th2))/2 + (dth3*l_J*m*cos(th5)*sin(th3))/2 - (dth2*l_B*m*cos(th2)*cos(th4)*sin(th5))/2 - (dth3*l_J*m*cos(th3)*cos(th4)*sin(th5))/2 + (dth1*l_B*m*cos(th2)*sin(th4)*sin(th5))/2 + (dth1*l_J*m*cos(th3)*sin(th4)*sin(th5))/2;
                                                                            2*d6^2*dth5*m*cos(th4)*cos(th5)^2 - (d6^2*dth5*m*cos(th4))/2 + (dd6*l_B*m*cos(th2)*cos(th4)*cos(th5))/2 + (dd6*l_J*m*cos(th3)*cos(th4)*cos(th5))/2 + 2*d6*dd6*m*cos(th4)*cos(th5)*sin(th5) - (d6^2*dth4*m*cos(th5)*sin(th4)*sin(th5))/2 - d6^2*dth1*m*cos(th4)*cos(th5)^2*sin(th4) - (3*d6*dth2*l_B*m*cos(th4)*cos(th5)*sin(th2))/2 - (d6*dth4*l_B*m*cos(th2)*cos(th5)*sin(th4))/2 - (d6*dth5*l_B*m*cos(th2)*cos(th4)*sin(th5))/2 - (3*d6*dth3*l_J*m*cos(th4)*cos(th5)*sin(th3))/2 - (d6*dth4*l_J*m*cos(th3)*cos(th5)*sin(th4))/2 - (d6*dth5*l_J*m*cos(th3)*cos(th4)*sin(th5))/2,                                                                                                                                                                                              (dd6*l_B*m*cos(th2)*cos(th5)*sin(th4))/2 + (d6*dth4*l_B*m*cos(th2)*cos(th4)*cos(th5))/2 - (d6*dth1*l_B*m*cos(th4)*cos(th5)*sin(th2))/2 - d6*dth2*l_B*m*cos(th5)*sin(th2)*sin(th4) - (d6*dth5*l_B*m*cos(th2)*sin(th4)*sin(th5))/2,                                                                                                                                                                                              (dd6*l_J*m*cos(th3)*cos(th5)*sin(th4))/2 + (d6*dth4*l_J*m*cos(th3)*cos(th4)*cos(th5))/2 - (d6*dth1*l_J*m*cos(th4)*cos(th5)*sin(th3))/2 - d6*dth3*l_J*m*cos(th5)*sin(th3)*sin(th4) - (d6*dth5*l_J*m*cos(th3)*sin(th4)*sin(th5))/2,                                                                                                                 -(m*cos(th5)*(dth1*l_B*cos(th2)*cos(th4) + dth1*l_J*cos(th3)*cos(th4) + dth2*l_B*cos(th2)*sin(th4) + dth3*l_J*cos(th3)*sin(th4)))/2,                                                                                                                                                                                                                                                                                   (d6*m*cos(th5)*(4*dd6*cos(th5) - 4*d6*dth5*sin(th5) - dth2*l_B*cos(th2)*cos(th4) - dth3*l_J*cos(th3)*cos(th4) + dth1*l_B*cos(th2)*sin(th4) + dth1*l_J*cos(th3)*sin(th4) + d6*dth1*sin(th4)*sin(th5)))/2,                                                                                                                                                                                                        (d6*m*(d6*dth1*cos(th4) + dth1*l_B*cos(th2)*cos(th4)*sin(th5) + dth1*l_J*cos(th3)*cos(th4)*sin(th5) + dth2*l_B*cos(th2)*sin(th4)*sin(th5) + dth3*l_J*cos(th3)*sin(th4)*sin(th5)))/2;
                                                                         (3*d6*dth2*l_B*m*sin(th2)*sin(th4)*sin(th5))/2 - (d6^2*dth4*m*cos(th4))/2 - d6^2*dth4*m*cos(th4)*cos(th5)^2 - (dd6*l_B*m*cos(th2)*sin(th4)*sin(th5))/2 - (dd6*l_J*m*cos(th3)*sin(th4)*sin(th5))/2 - d6*dth1*l_B*m*cos(th2)*cos(th5) - d6*dth1*l_J*m*cos(th3)*cos(th5) - d6^2*dth1*m*cos(th4)^2*cos(th5)*sin(th5) - (d6*dth4*l_B*m*cos(th2)*cos(th4)*sin(th5))/2 - (d6*dth5*l_B*m*cos(th2)*cos(th5)*sin(th4))/2 - (d6*dth4*l_J*m*cos(th3)*cos(th4)*sin(th5))/2 - (d6*dth5*l_J*m*cos(th3)*cos(th5)*sin(th4))/2 - 2*d6*dd6*m*sin(th4) + (3*d6*dth3*l_J*m*sin(th3)*sin(th4)*sin(th5))/2,                                                                                    (dd6*l_B*m*cos(th2)*cos(th4)*sin(th5))/2 - (dd6*l_B*m*cos(th5)*sin(th2))/2 - d6*dth2*l_B*m*cos(th2)*cos(th5) + (d6*dth5*l_B*m*sin(th2)*sin(th5))/2 + (d6*dth5*l_B*m*cos(th2)*cos(th4)*cos(th5))/2 - d6*dth2*l_B*m*cos(th4)*sin(th2)*sin(th5) - (d6*dth4*l_B*m*cos(th2)*sin(th4)*sin(th5))/2 + (d6*dth1*l_B*m*sin(th2)*sin(th4)*sin(th5))/2,                                                                                    (dd6*l_J*m*cos(th3)*cos(th4)*sin(th5))/2 - (dd6*l_J*m*cos(th5)*sin(th3))/2 - d6*dth3*l_J*m*cos(th3)*cos(th5) + (d6*dth5*l_J*m*sin(th3)*sin(th5))/2 + (d6*dth5*l_J*m*cos(th3)*cos(th4)*cos(th5))/2 - d6*dth3*l_J*m*cos(th4)*sin(th3)*sin(th5) - (d6*dth4*l_J*m*cos(th3)*sin(th4)*sin(th5))/2 + (d6*dth1*l_J*m*sin(th3)*sin(th4)*sin(th5))/2, (dth2*l_B*m*cos(th5)*sin(th2))/2 + (dth3*l_J*m*cos(th5)*sin(th3))/2 - (dth2*l_B*m*cos(th2)*cos(th4)*sin(th5))/2 - (dth3*l_J*m*cos(th3)*cos(th4)*sin(th5))/2 + (dth1*l_B*m*cos(th2)*sin(th4)*sin(th5))/2 + (dth1*l_J*m*cos(th3)*sin(th4)*sin(th5))/2,                                                                                                                                                                                                    (d6^2*dth1*m*cos(th4))/2 - d6^2*dth1*m*cos(th4)*cos(th5)^2 + d6^2*dth4*m*cos(th5)*sin(th5) + (d6*dth1*l_B*m*cos(th2)*cos(th4)*sin(th5))/2 + (d6*dth1*l_J*m*cos(th3)*cos(th4)*sin(th5))/2 + (d6*dth2*l_B*m*cos(th2)*sin(th4)*sin(th5))/2 + (d6*dth3*l_J*m*cos(th3)*sin(th4)*sin(th5))/2,                                                                                                                                                        -(d6*m*(dth2*l_B*sin(th2)*sin(th5) - 4*dd6 + dth3*l_J*sin(th3)*sin(th5) + dth2*l_B*cos(th2)*cos(th4)*cos(th5) + dth3*l_J*cos(th3)*cos(th4)*cos(th5) - dth1*l_B*cos(th2)*cos(th5)*sin(th4) - dth1*l_J*cos(th3)*cos(th5)*sin(th4)))/2];
 
 
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

 G = [                                0;
 (g*l_B*cos(th2)*(2*m + m_B + 2*m_J))/2;
         (g*l_J*cos(th3)*(2*m + m_J))/2;
                 -g*m*cos(th4)*cos(th5);
               d6*g*m*cos(th5)*sin(th4);
               d6*g*m*cos(th4)*sin(th5)];
   
% M(5:6,:) = M(5:6,:)/d6;
% C(5:6,:) = C(5:6,:)/d6;
% G(5:6) = G(5:6)/d6; 

u2_bar = G(2);
u3_bar = G(3);
u4_bar = -m*g;

% kp1 = 50; kp2 = 20; kp3 = 80; kp4 = 15;
% kd1 = 500; kd2 = 350; kd3 = 150; kd4 = 30;

kp1 = 50; kp2 = 20; kp3 = 80; kp4 = 10*0+15;
kd1 = 500; kd2 = 350; kd3 = 150; kd4 = 30;

delta_u1 = kp1*err_a - kd1*dq(1);
delta_u2 = kp2*err_b - kd2*dq(2);
delta_u3 = kp3*err_g - kd3*dq(3);
delta_u4 = kp4*err_l - kd4*dq(4);

u1 = delta_u1;
u2 = u2_bar + delta_u2;
u3 = u3_bar + delta_u3;
u4 = u4_bar + delta_u4;
   
input = [u1 u2 u3 u4 0 0]'; 




d2x(1:6) = inv(M)*(-C*dq -G + input)
d2x(7:12) = input;
